### ISSUE TITLE
Unknown column 'sha256_hash' in 'field list'

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SimpleDesk#124]
#### Description
Unknown column 'sha256_hash' in 'field list'
File: ...\Sources\Packages.php
Line: 1219

### Steps to reproduce
1. Just install the mod on cutting-edge build of SMF 2.1

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:

### Additional information/references

**Comment by XinYenFon** [comment]
Not sure if this is related to this issue (aka this issue happening because of the prio issue) but... 
![Annotation 2020-03-30 160010](https://user-images.githubusercontent.com/1669995/77915133-9990ed80-729f-11ea-83c3-604d35dabbf5.png)

**Comment by VBGAMER45** [comment]
This is an SMF issue fixed with latest version on github. It affected all packages.

https://github.com/SimpleMachines/SMF2.1/issues/6057
