### ISSUE TITLE
Wrong Version Reported

### ISSUE THREAD

**Issue by SugarD-x** [SimpleMachines/SimpleDesk#138]
#### Description
When using the SimpleDesk 2.1 RC1 release with SMF 2.1 RC3, SimpleDesk still incorrectly reports its version as "SimpleDesk 2.1 Beta 1" in the SimpleDesk administration section.

### Steps to reproduce
1. Install SimpleDesk 2.1 RC1 in SMF 2.1 RC3.
2. Check the version information in the SimpleDesk administration section.

### Environment (complete as necessary)
- Version/Git revision: v2.1/2.1-RC1 Tag
- Database Type: MySQL
- Database Version: MySQL Community Server 8.0.23

### Additional information/references
This is the same version number reported in SimpleDesk 2.1 Beta 1. It appears to be an update oversight in the SimpleDesk 2.1 RC1 release version.

**Comment by jdarwood007** [comment]
Fixed
