### ISSUE TITLE
SMF Unread helpdesk tickets overflows on mobile

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SimpleDesk#152]
#### Description
When on mobile if you visit ?action=unread, the table data will overflow.

This could be resolved with some CSS tricks

**Comment by DiegoAndresCortes** [comment]
Think I added this on my pr not sure

**Comment by jdarwood007** [comment]
Yea I just checked, it may be.  I need a few more prs committed, but I will test it more completely to be sure.
